### ISSUE TITLE
Version 1.1 crashes when exiting the application

### ISSUE THREAD

**Issue by muxi1** [vgmoose/vgedit#6]
vgedit v1.1 causes a system crash when closing the application in applet mode of the homebrew menu. Using the homebrew menu in high memory mode closes vgedit with an error message. This problem did not exist in version 1.0. Unfortunately version 1.0 does not have the hid fix and therefore cannot be controlled under the current ATM version.

ATM v0.10.2
FW 9.1.0 
hbmenu v3.2.0
nx-hbloader v2.3.0

**Comment by John2022** [comment]
Same here.
Right after editing without saving an ini file.

**Comment by muxi1** [comment]
@John2022 you can download a working version here:

[vgedit.zip](https://github.com/vgmoose/vgedit/files/4063947/vgedit.zip)

**Comment by vgmoose** [comment]
should be fixed now in 2.0
